### ISSUE TITLE
Docs: Workflow example for GitHub Action

### ISSUE THREAD

**Issue by ocean90** [wearerequired/coding-standards#63]
**Idea:**
For PRs, detect coding standard violations via PHP_CodeSniffer. Errors should prevent the PR from being merged and shown to the user.

**Implementation:**
* A [GitHub Action](https://help.github.com/en/actions) to set up PHP with Composer and to run `phpcs`
* To prevent the branch from being merged, use [protected branches](https://help.github.com/en/github/administering-a-repository/about-protected-branches) with `phpcs` as a [required status check](https://help.github.com/en/github/administering-a-repository/about-required-status-checks).
* Display errors via PR annotations in [Checks](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/about-status-checks#checks) via [cs2pr](https://github.com/staabm/annotate-pull-request-from-checkstyle)

**Result:**

```yml
name: PHP_CodeSniffer

on: pull_request

jobs:
  phpcs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.3'
          coverage: none
          tools: composer, cs2pr

      - name: Get Composer cache directory
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Setup cache
        uses: pat-s/always-upload-cache@v1.1.4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Install dependencies
        run: composer install --prefer-dist --no-suggest --no-progress

      - name: Detect coding standard violations
        run: vendor/bin/phpcs -nq --report=checkstyle | cs2pr
```

**Limits:**

* Only 10 warning annotations and 10 error annotations per step ([source](https://github.community/t5/GitHub-Actions/Maximum-number-of-annotations-that-can-be-created-using-GitHub/m-p/40663/highlight/true#M4310))
